server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5a30b0d4-b0e9-47e5-aab4-ca9c5535d940
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6397
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: clathpath:mapper/pms/**/*.xml
